import numpy as np
import os

"""
Simple straight-line track creator similar to skidpadCreator.py.

Generates a centerline as a straight segment (optionally angled),
writes file in the same "x y z q" format and can visualize it.
"""

# Defaults
DEFAULT_LENGTH = 500.0          # meters
DEFAULT_POINTS = 501            # number of centreline points (includes endpoints)
OUTPUT_FILENAME = "StraightLineTrack.txt"
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "datasets", "Tracks")


def generate_straight_centerline(length: float = DEFAULT_LENGTH,
                                 num_points: int = DEFAULT_POINTS,
                                 angle_deg: float = 90.0,
                                 start_at_origin: bool = True) -> np.ndarray:
    """
    Generate straight centerline points.

    Args:
        length: Length of the straight in meters.
        num_points: Number of points along the line (including start and end).
        angle_deg: Heading angle in degrees (0 = +X, 90 = +Y).
        start_at_origin: If True, start point is (0,0). Otherwise center the line at origin.

    Returns:
        N x 2 numpy array of x,y coordinates.
    """
    angles_rad = np.deg2rad(angle_deg)
    # param t from 0..1
    t = np.linspace(0.0, 1.0, num_points)
    half = length / 2.0

    # param along local x axis from -half .. +half or 0..length depending on start_at_origin
    if start_at_origin:
        s = t * length
        x_local = s
        y_local = np.zeros_like(s)
    else:
        s = (t - 0.5) * length
        x_local = s
        y_local = np.zeros_like(s)

    # rotate by angle
    cos_a = np.cos(angles_rad)
    sin_a = np.sin(angles_rad)
    x = x_local * cos_a - y_local * sin_a
    y = x_local * sin_a + y_local * cos_a

    return np.column_stack((x, y))


def write_track_file(coordinates: np.ndarray, output_path: str, track_name: str = "Straight Line Track"):
    """
    Write coordinates to file in the same format used by other creators:
    header and tab-separated columns: x y z q
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(": x y z q\n")
        f.write("#\n")
        f.write("#\n")
        f.write(f"# {track_name.upper()} TRACK COORDINATES\n")
        f.write("#\n")
        f.write("# Generated by straightLineCreator.py\n")
        f.write("#\n")
        f.write(f"# Length: {np.max(np.linalg.norm(np.diff(coordinates, axis=0), axis=1)):.3f} m (segment)\n")
        f.write("#\n")
        f.write("# x y z q\n")
        for x, y in coordinates:
            f.write(f"{x:.7f}\t{y:.7f}\t0\t0\n")
    print(f"Track file written to: {output_path}")
    print(f"Total points: {len(coordinates)}")


def visualize_straightline(coordinates: np.ndarray):
    """Simple matplotlib visualization (skips if matplotlib not installed)."""
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not installed, skipping visualization")
        return

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(coordinates[:, 0], coordinates[:, 1], '-k', linewidth=2, label='Centerline')
    ax.scatter(coordinates[0, 0], coordinates[0, 1], c='g', s=40, label='Start')
    ax.scatter(coordinates[-1, 0], coordinates[-1, 1], c='r', s=40, label='End')
    ax.set_aspect('equal', 'box')
    ax.set_xlabel('X (m)')
    ax.set_ylabel('Y (m)')
    ax.set_title('Straight Line Track Centerline')
    ax.grid(True, alpha=0.3)
    ax.legend()
    plt.tight_layout()
    plt.show()


def main():
    length = DEFAULT_LENGTH
    points = DEFAULT_POINTS
    angle_deg = 90.0           # create a north-pointing straight by default (along +Y)
    start_at_origin = True     # start at (0,0) and go forward

    coords = generate_straight_centerline(length=length, num_points=points,
                                         angle_deg=angle_deg, start_at_origin=start_at_origin)

    output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILENAME)
    write_track_file(coords, output_path, track_name="Straight Line")
    visualize_straightline(coords)


if __name__ == "__main__":
    main()